server:
  port: 8080

jwt:
  secret: secretkey1234

app:
  cors:
    allowedOrigins: http://localhost:5000

  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/spring
      username: postgres
      password: Password02117
      pool-size: 30